### ISSUE TITLE
Build cassé chez moi :-/

### ISSUE THREAD

**Issue by 0gust1** [ChtiJS/chtijs.francejs.org#40]
J'ai cloné un repo neuf pour  #39 .

J'ai une erreur bizarre dès le lancement, je vous met la fin du log : 

````
[20:05:41] Dev server listening on %d 35729
[gulp] Finished 'server' after 1.64 s
[20:05:41] chtijs.svg was reloaded.
<File "about.md" <Buffer 0a 0a 23 20 4e 6f  ...>> { title: 'Les habitudes de notre groupe',
  description: 'Pour mieux comprendre ChtiJS, découvrez nos petites habitudes.',
  shortTitle: 'Nos habitudes',
  shortDesc: 'Découvrir nos habitudes',
  keywords: [ 'JavaScript', 'groupe', 'Nord', 'Pas-de-Calais' ],
  lang: 'fr',
  location: 'FR',
  name: 'about',
  path: '/',
  ext: '.md',
  href: '/about.md' }
[20:05:41] favicon.png was reloaded.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-spawn'
/bin/sh: convert: command not found
cat: stdout: Broken pipe

    at Socket.<anonymous> (/Users/Gus/Sites/chtiJS_2/chtijs.francejs.org/node_modules/gulp-spawn/index.js:53:26)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13)
````

Bref, je comprend pas pourquoi `chtijs.svg` et `favicon.png`sont marquées en 'reloaded', au démarrage alors que je viens à peine de lancer la commande.

**Comment by nfroidure** [comment]
Il me semble que le souci a té réglé par ça ? 
# with OSX - http://www.imagemagick.org/script/binary-releases.php#macosx
brew install imagemagick --with-librsvg

@0gust1 reopen if not ;)

**Comment by 0gust1** [comment]
C'est bien ce que j'ai fait (cf mon dernier commentaire). Par contre, c'est possible qu'une update résolve le problème.

Dès que j'ai un peu de temps, je regarderais.
